### ISSUE TITLE
Add prominent links to repo/download/docker

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest-docs#101]
What links there be are not easy to find

**Comment by begriffs** [comment]
@ruslantalpa in the chat you mentioned:

> one thing i always find annoyng on postgret.com is that on homepage i don’t have direct links to repo/download/docker repo 

What do you have in mind? Should we re-order the sections so that Installation is first? Or maybe add links above the table of contents?

**Comment by ruslantalpa** [comment]
I think it's more about the first page. The absolutely first thing you see should not be the TOC especially since it's redundant, you have the same thing on the left. index should be a short overview of what it is with links to major related pages (git/docker ...)

The problem i am having is this (although might be unique to contributors). so i want to get to the git repo, i start typing "postgre..." hit enter, of course, the first item was postgrest.com and many times the github link is not even offered ... so now i have to either retype the full url, or remember to start typing "begriffs" to be presented with the github link

**Comment by begriffs** [comment]
👍 I get what you're saying. Let's see what I can do.

**Comment by steve-chavez** [comment]
A good reference for this would be https://hyperledger-fabric.readthedocs.io/en/release-1.2/ (links in the top-left corner).

To do it basically we need to add [layout.html](https://github.com/hyperledger/fabric/blob/release-1.2/docs/source/_templates/layout.html) under a `_templates/` dir, then style it and search some appropriate logos.

The goal should be having github repo(just main page, releases can be found from there), [docker hub](https://hub.docker.com/r/postgrest/postgrest/) and [gitter chat](https://gitter.im/begriffs/postgrest)(perhaps also stackoverflow link just like the reference).

Any help with this would be most appreciated.

**Comment by steve-chavez** [comment]
There are now some shields at the intro page but the links in the navbar would still be good to have.

**Comment by steve-chavez** [comment]
I think the shields have been good enough for this. Still, a different landing page could be a good idea. Though that would have to be a different issue.
