### ISSUE TITLE
Adding an advanced example on embedded ordering

### ISSUE THREAD

**Issue by skinkie** [PostgREST/postgrest-docs#115]
https://github.com/begriffs/postgrest/issues/1015

**Comment by begriffs** [comment]
It appears that the linked issue incorrectly uses `order_` rather than `order`. I'm closing this issue, but feel free to re-open if I have misunderstood.

Also thanks for thinking of the documentation and ways to improve it. Please open other docs issues (or send pull requests) if you notice things to be improved.

**Comment by skinkie** [comment]
No, "order_" is my column, "order" is the statement. I would like to see a simple example where is explained you should do film(*,actors(*)) as film.actors.order=name.

**Comment by begriffs** [comment]
Sorry about that, I read your url too quickly. Sure, we can add docs for ordering an embedded table. Actually, want to try Ruslan's suggestion in the linked issue and once you get things working for your app, maybe you could open a pull request against the docs?

**Comment by steve-chavez** [comment]
Will address on the tutorial for #75.
