### ISSUE TITLE
HOW-TO for SOAP?

### ISSUE THREAD

**Issue by fjf2002** [PostgREST/postgrest-docs#547]
Now that I have (almost) everything mentioned in https://github.com/PostgREST/postgrest/issues/2188, I can use SOAP.

Suggestion: I could add a HOW-TO for SOAP to the documentation?

By the way, I have noticed you have released PostgREST-Version 9.0.1 at docker hub, but without my XML PRs #2202 and #2300. Will they come later?

**Comment by steve-chavez** [comment]
> but without my XML PRs #2202 and #2300.

@fjf2002 Note that 9.0.1 actually doesn't contain any new feature, only [fixes](https://github.com/PostgREST/postgrest/blob/main/CHANGELOG.md#901---2022-06-03). We did it because a user was [asking for a patch release](https://github.com/PostgREST/postgrest/discussions/2289) and me and Wolfgang discussed that it's not ideal to do two consecutive major releases, we should provide at least one without a breaking change(patch or minor version release).

> Will they come later?

Of course, I just need to [provide a way forward](https://github.com/PostgREST/postgrest/issues/2144) from a breaking change I introduced. Then it would be good to release v10 and it will include [all of the unreleased features](https://github.com/PostgREST/postgrest/blob/main/CHANGELOG.md#unreleased).

> Suggestion: I could add a HOW-TO for SOAP to the documentation?

That would be amazing. I'm also interested in that one. Please go ahead!

**Comment by steve-chavez** [comment]
@fjf2002 Btw, note that the latest pre-release does include the unreleased features. It's uploaded on dockerhub too.

- https://github.com/PostgREST/postgrest/releases/tag/v9.0.0.20220531
- https://hub.docker.com/layers/postgrest/postgrest/postgrest/v9.0.0.20220531/images/sha256-243482ed04fa99e115a003be226743e1edc31d4bcd42ee1652d3a6a3ba69cf18?context=explore

**Comment by fjf2002** [comment]
Thanks for the clarification. https://github.com/PostgREST/postgrest/pull/2300 is still missing in v9.0.0.20220531, but no need to hurry.

**Comment by steve-chavez** [comment]
> The thing is, the average SOAP request is made without a line Accept: text/xml. So the SOAP How-To would include this dirty "add Accept: text/xml in the reverse proxy, when making the request" stuff.

@fjf2002 I see. The above would be acceptable, the [how-to for img](https://postgrest.org/en/stable/how-tos/providing-images-for-img.html) also has some Nginx stuff(removed on [latest](https://postgrest.org/en/latest/how-tos/providing-images-for-img.html))

> The other solution would of course be, solving https://github.com/PostgREST/postgrest/pull/1582, at least the case with single unnamed xml parameter and scalar xml return value.

I've also added a coment on https://github.com/PostgREST/postgrest/pull/1582#issuecomment-1154431651, perhaps we can move it forward with that.

**Comment by fjf2002** [comment]
Meanwhile, this SOAP docs are active. Closing ticket.
