### ISSUE TITLE
Bulk update attempt without including PK column overwrites entire table

### ISSUE THREAD

**Issue by mdr1384** [PostgREST/postgrest-docs#599]
### Environment

* PostgreSQL version: 13.10
* PostgREST version: 10.1.2
* Operating system: FreeBSD

### Description of issue

Possibly just a documentation deficiency...

In [the UPDATES section](https://postgrest.org/en/stable/api.html?highlight=csv#updates) it states:

> Doing a full table update without filters is not allowed and will result in 0 updated rows. To make a an update without filters, you must limit the rows affected. See [Limited Updates/Deletions](https://postgrest.org/en/stable/api.html?highlight=csv#limited-update-delete).

Well I tested that and found that unless you specify a primary/unique key column in the body, it will in fact **_update ALL your rows_**. Not sure if that is expected, but it sure is dangerous.

```
create table api.test (id int, val text, pid serial primary key);
CREATE TABLE
insert into api.test (id, val) select generate_series(1,100000), md5(random()::text);
INSERT 0 100000
```
```
> PATCH /api.test
> [{"id": 1, "val": "test1"}, {"id": 2, "val": "test2"}]
< 204 No Content

> HEAD Prefer: count=exact /api/test?val=eq.test1
< 200 OK Content-Range: 0-99999/100000

> HEAD Prefer: count=exact /api/test?id=neq.1
< 200 OK Content-Range: */0
```
Yikes!

Using the primary key in the body prevents disaster:

```
truncate api.test;
TRUNCATE TABLE
insert into api.test (id, val) select generate_series(1,100000), md5(random()::text);
INSERT 0 100000
```
```
> PATCH /api.test
> [{"pid": 100001, "val": "test1"}, {"pid": 100002, "val": "test2"}]
< 409 Conflict

> HEAD Prefer: count=exact /api/test?val=eq.test1
< 200 OK Content-Range: */0
```

**Comment by laurence-isla** [comment]
It looks like there was an oversight in the docs that was added after the Bulk Update was implemented, and ended in the `stable` branch.  That feature (Bulk Update) was reverted due to some issues that were discussed here: https://github.com/PostgREST/postgrest/pull/2414#issuecomment-1212647377. 

> Doing a full table update without filters is not allowed and will result in 0 updated rows. To make a an update without filters, you must limit the rows affected. See [Limited Updates/Deletions](https://postgrest.org/en/stable/api.html?highlight=csv#limited-update-delete).

This needs to change to the warning it had before and link to https://postgrest.org/en/stable/admin.html?highlight=block%20fulltable#block-full-table-operations

> Not sure if that is expected, but it sure is dangerous.

Yes, right now that is expected. The link above is useful to prevent this.

> Using the primary key in the body prevents disaster:

Yes, but it's not because it works doing a Bulk Update, right now that feature is not implemented, but  because it's trying to update the whole table with the same `pid`, which gives an error (hence the `409 Conflict` response) . But you're right, this is very misleading so it will be reverted ASAP.
